name: github pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0

      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main

      - name: Run duration-length script
        run: nix develop --command bash -x ./scripts/duration-length.sh

      # deploy to duration-length-content branch in local repository
      - name: deploy duration-length-content branch
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: duration-length-content
          FOLDER: content
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Clone ox-hugo
        run: git clone https://github.com/jsntn/ox-hugo.git ox-hugo

      - name: Build
        run: nix develop --command hugo --minify

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          cname: shufang.org

      - name: Deploy to production server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          port: ${{ secrets.PORT }}
          script: cd ${{ secrets.WEBSITE_ABS_PATH }}; git pull
